# Generated by Django 4.1.6 on 2023-07-11 01:09

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to=recipe.models.Recipe.fileName)),
                ('recipe_description', models.CharField(max_length=500)),
                ('recipe_ingredients', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
