# Generated by Django 4.1.6 on 2023-07-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_instructions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
